<a href="https://colab.research.google.com/github/Geek-a-Byte/ML-sessional/blob/main/lab4/lasso_ridge_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load and read Dataset

In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
df = fetch_california_housing()

In [44]:
df.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [45]:
dataset = pd.DataFrame(df.data)
dataset.columns = df.feature_names

In [46]:
dataset

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [47]:
dataset["Price"] = df.target

In [48]:
dataset

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  Price  
0        -122.23  4.526  
1        -122.22  3.585  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20640 rows x 9 columns]

In [49]:
X = dataset.iloc[:,:-1] # independent features
y = dataset.iloc[:,-1] # dependent features

# X = dataset[dataset.drop(columns=['Price'])]
# y = dataset["Price"]

In [50]:
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [13]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Price, Length: 20640, dtype: float64

## Split 

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2,random_state=42)

## Model FIt

In [52]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=6, include_bias=False)

poly_features_train = poly.fit_transform(X_train)
poly_features_test = poly.fit_transform(X_test)

# x + x^2 + x^3 , shudhu train data ke fit transform korabo, y ke na

poly_regressor = LinearRegression()
poly_regressor.fit(poly_features_train,y_train)

y_pred_linear=poly_regressor.predict(poly_features_test)
y_pred_linear

array([0.11872414, 1.68064309, 3.0955044 , ..., 5.49914942, 0.88255035,
       1.47698603])

In [53]:
poly

PolynomialFeatures(degree=6, include_bias=False)

In [54]:
poly_features_train

array([[ 3.25960000e+00,  3.30000000e+01,  5.01765650e+00, ...,
         2.00701172e+11, -7.18069647e+11,  2.56911314e+12],
       [ 3.81250000e+00,  4.90000000e+01,  4.47354497e+00, ...,
         2.22302348e+11, -7.77827820e+11,  2.72159121e+12],
       [ 4.15630000e+00,  4.00000000e+00,  5.64583333e+00, ...,
         2.53114458e+11, -8.79839292e+11,  3.05836809e+12],
       ...,
       [ 2.93440000e+00,  3.60000000e+01,  3.98671727e+00, ...,
         2.27424496e+11, -7.91140518e+11,  2.75213678e+12],
       [ 5.71920000e+00,  1.50000000e+01,  6.39534884e+00, ...,
         3.12451932e+11, -1.01401377e+12,  3.29082277e+12],
       [ 2.57550000e+00,  5.20000000e+01,  3.40257649e+00, ...,
         3.20408088e+11, -1.03850564e+12,  3.36600108e+12]])

## Lasso and Ridge Regression

In [55]:
from sklearn.linear_model import Lasso
lasso_regressor = Lasso(alpha=0.5)
lasso_regressor.fit(X_train, y_train)
y_pred_lasso = lasso_regressor.predict(X_test)

In [56]:
from sklearn.linear_model import Ridge
ridge_regressor = Ridge(alpha=0.5)
ridge_regressor.fit(X_train, y_train)
y_pred_ridge = ridge_regressor.predict(X_test)

### coeff

In [57]:
poly_regressor.coef_

array([-7.99920977e-12,  4.34501391e-12,  1.67558971e-14, ...,
       -8.04686065e-12,  1.20347336e-11,  6.52526494e-12])

In [58]:
lasso_regressor.coef_

array([ 2.91076149e-01,  1.19817671e-02,  0.00000000e+00, -0.00000000e+00,
        9.94733255e-06, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00])

In [59]:
ridge_regressor.coef_

array([ 4.48592822e-01,  9.72511153e-03, -1.23168574e-01,  7.82279875e-01,
       -2.02771791e-06, -3.52608828e-03, -4.19789745e-01, -4.33694467e-01])

### score

In [60]:
print(poly_regressor.score(poly_features_train,y_train))
print(poly_regressor.score(poly_features_test,y_test))

0.029814899503239345
-3136.0359638173745


In [61]:
print(lasso_regressor.score(X_train,y_train))
print(lasso_regressor.score(X_test,y_test))

0.45774275748745574
0.44572168363924836


In [62]:
print(ridge_regressor.score(X_train,y_train))
print(ridge_regressor.score(X_test,y_test))

0.6125511746425621
0.5758213996714421


### rmse

In [63]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_test,y_pred_linear)
mse = mean_squared_error(y_test,y_pred_linear)
rmse= np.sqrt(mse)
print(f'Mean absolute error: {mae:.2f}')
print(f'Mean squared error: {mse:.2f}')
print(f'rmse:{rmse: .2f}')

Mean absolute error: 1.88
Mean squared error: 4110.80
rmse: 64.12


In [64]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_test,y_pred_lasso)
mse = mean_squared_error(y_test,y_pred_lasso)
rmse= np.sqrt(mse)
print(f'Mean absolute error: {mae:.2f}')
print(f'Mean squared error: {mse:.2f}')
print(f'rmse:{rmse: .2f}')

Mean absolute error: 0.65
Mean squared error: 0.73
rmse: 0.85


In [65]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_test,y_pred_ridge)
mse = mean_squared_error(y_test,y_pred_ridge)
rmse= np.sqrt(mse)
print(f'Mean absolute error: {mae:.2f}')
print(f'Mean squared error: {mse:.2f}')
print(f'rmse:{rmse: .2f}')

Mean absolute error: 0.53
Mean squared error: 0.56
rmse: 0.75
